### ISSUE TITLE
STW News still says undefined

### ISSUE THREAD

**Issue by RiftSTW** [Horziox/Kevin#4]
I'm still getting gifs from the stw news and the titles are still saying undefined I tried to fix it myself but I'm not getting any luck
and BR and Creative are getting the same issue too

**Comment by RiftSTW** [comment]
![stw-news](https://user-images.githubusercontent.com/33435468/107262518-454db280-6a06-11eb-8e06-267323d041f0.gif)
![creative-news](https://user-images.githubusercontent.com/33435468/107262531-4848a300-6a06-11eb-8cf2-0aede0aada88.gif)
![br-news](https://user-images.githubusercontent.com/33435468/107262542-4a126680-6a06-11eb-9a6f-5a8da1b12241.gif)

**Comment by Horziox** [comment]
I check ^^

**Comment by Horziox** [comment]
Normally everything is ok !
